# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: sample_app_development
  encoding: utf8
  collation: utf8_general_ci


test:
  adapter: mysql2
  database: sample_app_test
  encoding: utf8
  collation: utf8_general_ci  

production:
  adapter: mysql2
  database: sample_app_production
  encoding: utf8
  collation: utf8_general_ci  

